services:
  portainer:
    image: portainer/portainer-ce:2.27.0
    container_name: portainer
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dagobah_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.fiftyfifty90.com`)"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:
  
networks:
  dagobah_proxy:
    name: dagobah_proxy
    external: true
