services:
  portainer:
    image: portainer/portainer-ce:2.20.0
    container_name: portainer_git
    restart: always
    ports:
      - 8001:8000
      - 9444:9443
      - 9001:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dagobah_proxy

volumes:
  portainer_data:
  
networks:
  dagobah_proxy:
    name: dagobah_proxy
    external: true
